#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "meelo"
name = "Meelo"
description.en = "Music Server, focused on metadata integration & UI"

version = "1.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-3.0"
code = "https://github.com/Arthi-chaud/Meelo"
fund = "https://github.com/sponsors/Arthi-chaud"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/meelo"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Arthi-chaud/Meelo/archive/refs/tags/v3.11.0.tar.gz"
    sha256 = "7dcbf1531c0c8086107d1fb9d953e3a4d599ea631c62d67ed08a32378c9468e9"

    autoupdate.strategy = "latest_github_release"

    [resources.sources.meili]
    amd64.url = "https://github.com/meilisearch/meilisearch/releases/download/v1.43.0/meilisearch-linux-amd64"
    amd64.sha256 = "3583ed1260dd71fdc7645ab9abcc3cdf7002758cbb877f0cf905671c9c747645"
    arm64.url = "https://github.com/meilisearch/meilisearch/releases/download/v1.43.0/meilisearch-linux-aarch64"
    arm64.sha256 = "b4e419798312b96d67ad575d6fb1f4f9e32f8ce562af2e40d6c9dcecaac256cc"
    rename = "meilisearch"
    in_subdir = false
    extract = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/meilisearch/meilisearch"
    autoupdate.asset.amd64 = "^meilisearch-linux-amd64$"
    autoupdate.asset.arm64 = "^meilisearch-linux-aarch64$"

    [resources.sources.gocv]
    amd64.url = "gocv/opencv:4.13.0"
    amd64.sha256 = "aa3ff9b79b042385a208728ad92f562f1006f7af871de47d0297560a9654903f"
    arm64.url = "ghcr.io/toeverything/affine:0.26.3"
    arm64.sha256 = "aa3ff9b79b042385a208728ad92f562f1006f7af871de47d0297560a9654903f"

    format = "docker"
    extract = true
    prefetch = false

    autoupdate.strategy = "latest_github_tag"
    autoupdate.upstream = "https://github.com/hybridgroup/gocv"


    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000
    api.default = 4000
    scanner.default = 5000
    matcher.default = 6789

    [resources.apt]
    packages = "postgresql, postgresql-contrib, postgresql-postgis, python3, python3-venv, ffmpeg, libopencv-dev"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"

    [resources.go]
    version = "1.25.0"