location __PATH__/ {

  proxy_pass       http://127.0.0.1:__PORT__/;

  include proxy_params_no_auth;
}

location = __PATH__/api {
  return 302 /api/;
}

location __PATH__/api/ {
  proxy_pass http://127.0.0.1:__PORT_API__/;
}

location = __PATH__/scanner {
  return 302 /scanner/;
}

location __PATH__/api/ {
  proxy_pass http://127.0.0.1:__PORT_SCANNER__/;
}

location = __PATH__/matcher {
  return 302 /matcher/;
}

location __PATH__/api/ {
  proxy_pass http://127.0.0.1:__PORT_MATCHER__/;
}