#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=key --value=$key

meili_master_key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=meili_master_key --value=$meili_master_key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"/prebuild
ynh_setup_source --dest_dir="$install_dir/meilisearch" --source_id="meili"

chmod +x "$install_dir/meilisearch/meilisearch"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# BUILDING SOURCES AND SETTING UP THE SERVER
#=================================================
ynh_script_progression "Installing dependencies..."

#ynh_script_progression "Building server..."
#pushd "$install_dir"/server
#    ynh_hide_warnings corepack enable && corepack prepare yarn --activate
#    ynh_hide_warnings ynh_exec_as_app NODE_ENV=production CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" yarn workspaces focus
#    ynh_hide_warnings ynh_exec_as_app NODE_ENV=production CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" yarn install --immutable
#    ynh_hide_warnings ynh_exec_as_app NODE_ENV=production CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" yarn run build && yarn workspaces focus --all --production
#popd

mv $install_dir/prebuild/server $install_dir/server

#ynh_script_progression "Building front..."
#pushd "$install_dir"/front
#    ynh_hide_warnings ynh_exec_as_app NODE_ENV=production CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" yarn workspaces focus -A 
#    ynh_hide_warnings ynh_exec_as_app NODE_ENV=production CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" yarn build:web
#popd
mv $install_dir/prebuild/front $install_dir/front

mkdir $install_dir/matcher
ynh_script_progression "Building matcher..."
pushd "$install_dir"/prebuild/matcher
    ynh_exec_as_app python3 -m venv $install_dir/matcher/venv
    ynh_hide_warnings ynh_exec_as_app "$install_dir/matcher/venv/bin/pip" install --upgrade pip 
    ynh_hide_warnings ynh_exec_as_app "$install_dir/matcher/venv/bin/pip" install -r ./requirements.txt
popd

ynh_script_progression "Prepare scanner deps..."
ynh_setup_source --dest_dir="$install_dir/gocv" --source_id="gocv"

mkdir $install_dir/scanner
ynh_script_progression "Building scanner..."
pushd "$install_dir"/prebuild/scanner
    ynh_hide_warnings ynh_exec_as_app bash dl_watcher.sh
    ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=1 CGO_CXXFLAGS="-std=c++17" GOOS=linux go mod download
    ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=1 CGO_CXXFLAGS="-std=c++17" GOOS=linux go build -o "$install_dir/scanner/scanner" ./app
popd

chown -R $app:$app "$install_dir/"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}-server" --template="meelo-server.service"
ynh_config_add_systemd --service="${app}-web" --template="meelo-web.service"
ynh_config_add_systemd --service="${app}-matcher" --template="meelo-matcher.service"
ynh_config_add_systemd --service="${app}-scanner" --template="meelo-scanner.service"

yunohost service add "${app}-server" --description="Meelo main service" --log="/var/log/$app/$app-server.log"
yunohost service add "${app}-web" --description="Meelo main service" --log="/var/log/$app/$app-web.log"
yunohost service add "${app}-matcher" --description="Meelo matcher service" --log="/var/log/$app/$app-matcher.log"
yunohost service add "${app}-scanner" --description="Meelo scanner service" --log="/var/log/$app/$app-scanner.log"

ynh_config_add_logrotate
touch /var/log/$app/$app-server.log
touch /var/log/$app/$app-web.log
touch /var/log/$app/$app-matcher.log
touch /var/log/$app/$app-scanner.log
chown -R $app:$app /var/log/$app/

# Create a dedicated Fail2Ban config
#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="${app}-server" --action="start"
ynh_systemctl --service="${app}-web" --action="start"
ynh_systemctl --service="${app}-matcher" --action="start"
ynh_systemctl --service="${app}-scanner" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
