#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

#ynh_config_remove_fail2ban

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status "${app}-server" >/dev/null; then
	yunohost service remove "${app}-server"
fi

if ynh_hide_warnings yunohost service status "${app}-web" >/dev/null; then
	yunohost service remove "${app}-web"
fi

if ynh_hide_warnings yunohost service status "${app}-matcher" >/dev/null; then
	yunohost service remove "${app}-matcher"
fi

if ynh_hide_warnings yunohost service status "${app}-scanner" >/dev/null; then
	yunohost service remove "${app}-scanner"
fi

ynh_config_remove_systemd "${app}-server"
ynh_config_remove_systemd "${app}-web"
ynh_config_remove_systemd "${app}-matcher"
ynh_config_remove_systemd "${app}-scanner"

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
